### ISSUE TITLE
Servable.create metadata support

### ISSUE THREAD

**Issue by KineticCookie** [Hydrospheredata/hydro-serving-sdk#21]

**Comment by KineticCookie** [comment]
Manager API doesn't return metadata field. Need to fix it.

See issue https://github.com/Hydrospheredata/hydro-serving-manager/issues/32

**Comment by KineticCookie** [comment]
@trthhrtz can you also implement fallback strategy for metadata field, in case manager doesn't contain the fix for this issue?

In that case,we  could probably just default the field to empty dictionary.

**Comment by trthhrtz** [comment]
@KineticCookie Fixed
