### ISSUE TITLE
High level interface to send requests to models

### ISSUE THREAD

**Issue by KineticCookie** [Hydrospheredata/hydro-serving-sdk#23]
Currently we have GRPC service definitions and HTTP endpoint for gateway.
GRPC operates on proto messages which are not convenient to use in Python. And JSON requires de-/serializers to use with numpy types.

We need to design an interface to seamlessly intregrate numpy/pandas data types and send to model data ingestion.

**Comment by KineticCookie** [comment]
The same serving interface could be used for local model serving #7

**Comment by Valenzione** [comment]
Fixed in [2.3.0 release](https://github.com/Hydrospheredata/hydro-serving-sdk/releases/tag/2.3.0) 👍
